[package]
name = "native_api_1c_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.28", features = ["full"] }
quote = "1.0.32"
proc-macro2 = "1.0.66"
# TODO
