name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Install mingw-w64
      run: sudo apt-get -y install mingw-w64
    - name: Install target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --target=x86_64-pc-windows-gnu --verbose
    - name: Run tests
      run: cargo test --verbose
